### PR TITLE
Fix null robot

### LINKED ISSUE #897: Exception Thrown when Placing a Robo Dozer
Encountered a bug when playing today. My colony had matured quite a bit and I was placing a robot on Underground Level 1 while in quick succession trying to end the turn and crashed the game. I don't know if it crashed during robot placement or when I pushed the enter key to try and step to the next turn.

**OS:** Windows 10 64 bit
**Version:** Current build of master branch on 23May
**Compilation:** Debug x64 using VS2019

**Exception Message**: Exception thrown: write access violation. **this** was nullptr.

**Call Stack**
OPHD.exe!Robot::startTask(int turns) Line 18	C++
OPHD.exe!MapViewState::placeRobodozer(Tile & tile) Line 973	C++
OPHD.exe!MapViewState::placeRobot() Line 1098	C++
OPHD.exe!MapViewState::onMouseDown(NAS2D::EventHandler::MouseButton button, int __formal, int __formal) Line 629	C++
OPHD.exe!NAS2D::DelegateX<void,enum NAS2D::EventHandler::MouseButton,int,int>::operator()(NAS2D::EventHandler::MouseButton <params_0>, int <params_1>, int <params_2>) Line 429	C++
OPHD.exe!NAS2D::Signal<enum NAS2D::EventHandler::MouseButton,int,int>::emit(NAS2D::EventHandler::MouseButton <params_0>, int <params_1>, int <params_2>) Line 43	C++
OPHD.exe!NAS2D::Signal<enum NAS2D::EventHandler::MouseButton,int,int>::operator()(NAS2D::EventHandler::MouseButton <params_0>, int <params_1>, int <params_2>) Line 44	C++
OPHD.exe!NAS2D::EventHandler::pump() Line 684	C++
OPHD.exe!NAS2D::StateManager::update() Line 88	C++
OPHD.exe!SDL_main(int argc, char * * argv) Line 159	C++
OPHD.exe!main_getcmdline() Line 71	C
OPHD.exe!main(int argc, char * * argv) Line 87	C
[External Code]

RobotPlacementException
Disassembly View
Screenshot

### PR DESCRIPTION
**Pull request by ldicker83**
Closes #897

### CODE REVIEW

File: OPHD/States/MapViewState.cpp [hunk 1]
```diff
@@ -993,9 +993,12 @@ void MapViewState::populateRobotMenu()
 {
 	mRobots.clear();
 
-	for (auto item : RobotMetaTable)
+	for (auto& item : RobotMetaTable)
 	{
-
+		if (mRobotPool.robotAvailable(item.first))
+		{
+			mRobots.addItemSorted(item.second.name, item.second.sheetIndex, static_cast<int>(item.first));
```
Comment (DanRStevens) [inline OPHD/States/MapViewState.cpp:1000]: I recommend using structured bindings to give better names than `first` and `second`:
```cpp
for (auto& [robotType, robotMeta] : RobotMetaTable)
{
	if (mRobotPool.robotAvailable(robotType))
	{
		mRobots.addItemSorted(robotMeta.name, robotMeta.sheetIndex, static_cast<int>(robotType));
	}
}
```

**Review by DanRStevens — APPROVED** [review]

File: OPHD/States/MapViewState.cpp (hunk 1 above)
Comment (ldicker83) [reply OPHD/States/MapViewState.cpp:1000]: Good point, I keep forgetting I can do that. Will make a commit to address that now.

**Review by DanRStevens — APPROVED** [review]
