### PR TITLE
Fix misreported warehouse usage

### LINKED ISSUE #960: Warehouse Storage misrepresented in full-screen UI
Storage space in the Warehouse fullscreen report is misrepresented in the visual representation of the bars.

### PR DESCRIPTION
**Pull request by ldicker83**
Closes #960

### CODE REVIEW

File: OPHD/UI/ProductListBox.cpp [hunk 1]
```diff
@@ -26,15 +26,19 @@ void ProductListBox::productPool(ProductPool& pool)
...
 	clear();
 
-	for (std::size_t product_type = 0; product_type < static_cast<std::size_t>(ProductType::PRODUCT_COUNT); ++product_type)
+	const auto totalProducts = static_cast<std::size_t>(ProductType::PRODUCT_COUNT);
+
+	for (std::size_t product_type = 0; product_type < totalProducts; ++product_type)
 	{
-		const auto productCount = pool.count(static_cast<ProductType>(product_type));
+		const auto productType = static_cast<ProductType>(product_type);
+		const auto productCount = pool.count(productType);
```
Comment (DanRStevens) [inline OPHD/UI/ProductListBox.cpp:34]: Variable names could probably be improved here.

I find `totalProducts` to be a bit misleading of a name. It's basically the number of product types. Maybe `productTypeCount`?

There is both a `product_type` and a `productType`. I would be tempted to rename `product_type` to `productTypeIndex`.

File: OPHD/UI/ProductListBox.cpp [hunk 2]
```diff
@@ -26,15 +26,19 @@ void ProductListBox::productPool(ProductPool& pool)
...
+
 		if (productCount > 0)
 		{
 			ProductListBoxItem* item = new ProductListBoxItem();
-			item->text = productDescription(static_cast<ProductType>(product_type));
+			item->text = productDescription(productType);
 			item->count = productCount;
-			item->usage = static_cast<float>(productCount) / static_cast<float>(pool.capacity());
+			item->usage = static_cast<float>(productCount * pool.productStorageRequirement(productType)) / static_cast<float>(pool.capacity());
```
Comment (DanRStevens) [inline OPHD/UI/ProductListBox.cpp:41]: If you want to avoid `float`, you can pre-multiply before the divide:
```cpp
const auto percent = value * 100 / capacity;
```
That would allow `int` values to be used just as effectively.

File: OPHD/UI/ProductListBox.cpp (hunk 1 above)
Comment (ldicker83) [reply OPHD/UI/ProductListBox.cpp:34]: I agree. I didn't want to spend too much time on it but I noticed that naming was a little weird here.
